Movie Web Application/web_application/web_project/credentials/urls.py
from django.urls import path
from . import views




app_name = 'credentials'  # ---> NameSpace




urlpatterns = [

    path('', views.user_movies, name='user_movies'),
    # Other URL patterns for your second app

    path("signup", views.register_request, name="signup"),
    path("signin", views.login_request, name="signin")
]

Movie Web Application/web_application/web_project/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'  # ---> NameSpace
urlpatterns = [

    path('', views.index, name='home'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('login/',views.login,name='login'),
    # path('sign',views.sign,name='sign'),
    path('add/',views.add_movies,name='add_movies'),
    path('update/<int:id>',views.update,name='updates'),
    path('movies',views.movies,name='movies'),
    path('mail',views.profiles,name='profiles'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('user',views.user,name='user'),


]

Movie Web Application/web_application/web_project/web_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('credentials/',include('credentials.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Movie Web Application/web_application/web_project/credentials/models.py
from django.db import models

# Create your models here.

Movie Web Application/web_application/web_project/myapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):

    name = models.CharField(max_length=250)
    desc = models.TextField(max_length=250)
    year = models.DateField()
    img = models.ImageField(upload_to='movies')

    def __str__(self):
        return self.name


class Profile(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

Movie Web Application/web_application/web_project/myapp/forms.py
from django import forms
from .models import Movie

class DateInput(forms.DateInput):
    input_type = 'date'

class AddMovies(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

        widgets = {
            'year':DateInput

        }
        labels = {
            'name':"Movie Name:",
             'desc':"Movie Description",
             'year':"Movie Year",
              'img':"Move Poster"
        }

Movie Web Application/web_application/web_project/credentials/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .r_forms import NewUserForm

from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("credentials:user_movies")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="sign_up.html", context={"form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("credentials:user_movies")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="sign.html", context={"login_form": form})


def user_movies(request):
    return render(request, 'index.html')

Movie Web Application/web_application/web_project/myapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Movie
from .forms import AddMovies


# Create your views here.

def index(request):
    movie = Movie.objects.all()
    context = {'movie_list': movie}
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movie})


def login(request):
    return render(request, 'login.html')


def sign(request):
    return render(request, 'sign.html')


def add_movies(request):
    if request.method == "POST":
        form = AddMovies(request.POST or None, request.FILES)
        movie = Movie(form)
        if form.is_valid():
            movie.save()
    form = AddMovies()
    dict_form = {'form': form}

    return render(request, 'add.html', dict_form)


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = AddMovies(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return render(request, 'confirmation.html')

    return render(request, 'update.html', {'form': form, 'movie': movie})


def movies(request):
    dict_movies = {'movies': Movie.objects.all()}
    return render(request, 'movies.html', dict_movies)


def profiles(request):
    email = "jeminmthw997@gmail.com"
    return HttpResponseRedirect("https://www.gmail.com")

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

def user(request):
    return render(request,'user.html')

Movie Web Application/web_application/web_project/templates/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Add Movies
{% endblock %}
{% block style %}
.custom-rounded {
  border-radius: 10px;
}
.bg-opacity {
  background-color: rgba(0, 0, 0, 0.5); /* Black color with 70% opacity */
  color: white; /* Text color */
}
{% endblock %}
{% block content %}
<div class="container w-25 text-center  p-3 bg-opacity custom-rounded ">

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy }}
<button type="submit" class="btn btn-warning btn-lg btn-block mb-4">
  Submit
</button>

</form>



</div>

{% endblock %}

Movie Web Application/web_application/web_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">


<html>
<head>
  <title>{% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  <style>
      body {
      margin: 0;
      padding: 0;
    }

     .black-yellow-section {
      background: linear-gradient(45deg, black, yellow);
      padding: 100px;
      color: white;
      min-height: calc(100vh - 56px - 100px); /* Subtract navbar height and padding */
    }

        .social-icons {
      list-style: none;
      padding: 0;
      display: flex;
      justify-content: center;
      margin-top: 10px;
    }

    .social-icons li {
      margin-right: 10px;
    }

    .social-icons li:last-child {
      margin-right: 0;
    }

    .social-icons a {
      color: #fff;
      text-decoration: none;
      font-size: 20px;
    }


{% block style %} {% endblock %}

  </style>
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" >
    <!-- Navbar content -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container">
    <a class="navbar-brand" href="{% url 'myapp:home' %}">Movie Bazar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link text-warning" href="{% url 'myapp:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'myapp:user' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'myapp:movies' %}">Movies</a>
        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'credentials:signup' %}">Sign Up</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

  </nav>

  <div class="black-yellow-section">
     {% block content %}

  <!-- Black and Yellow Section -->











 {% endblock %}
</div>

  <!-- Footer -->
  <footer class="bg-dark text-white text-center p-3 fixed-bottom">
     <footer class="footer" >
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 Jemin Mathew. All rights reserved.</p>
        </div>
        <div class="col-md-6">
          <ul class="social-icons">
            <li><a href="mailto:jeminthw997@gmail.com"><i class="far fa-envelope"></i>Gmail</a></li>


            <li><a href="https://www.linkedin.com/in/jemin-mathew-584908279"><i class="fab fa-linkedin"></i>Linkedin</a></li>

            <li><a href="https://github.com/JeminGitHub"><i class="fab fa-github"></i>GitHub</a></li>

          </ul>
        </div>
      </div>
    </div>
  </footer>
  </footer>

  <!-- Bootstrap JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/your-font-awesome-kit.js" crossorigin="anonymous"></script>
</body>

</html>

Movie Web Application/web_application/web_project/templates/confirmation.html
{% extends "base.html" %}

{% block title %} Confirmation {% endblock %}

{% block style %}
  .custom-alert {
    background-color: rgba(0, 0, 0, 0.6); /* Black color with 60% opacity */
    color: white; /* Text color */
  }


{% endblock %}
{% block content %}




<div class="container bg-opacity">
  <div class="alert custom-alert text-white text-center" role="alert">
    <h4>Thank You For Your Contribution. Updated Successfully!</h4>
  </div>
</div>




{% endblock %}

Movie Web Application/web_application/web_project/templates/delete.html
{% extends "base.html" %}

{% block title %} Confirmation {% endblock %}

{% block style %}
  .custom-alert {
    background-color: rgba(0, 0, 0, 0.6);
    color: white;
  }


{% endblock %}
{% block content %}




<div class="container bg-opacity">

  <div class="alert custom-alert text-white text-center" role="alert">
    <form method="POST">
      {% csrf_token %}
    <h4>Are You Sure Want You Delete!</h4>
       <button type="submit" class="btn btn-danger">Delete</button>
      </form>
  </div>
</div>




{% endblock %}

Movie Web Application/web_application/web_project/templates/details.html
{% extends "base.html" %}

{% block title %}Home {% endblock %}
{% block style %}

{% endblock %}
{% block content %}



<!--<div class="card bg-dark text-yellow" style="width: 20rem; ">-->
<!--    <img src="{{movie.img.url}}" class="card-img-top" alt="...">-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">{{movie.name}}</h5>-->
<!--      <h6 class="card-title">{{movie.year}}</h6>-->
<!--    <p class="card-text">{{movie.desc}}</p>-->
<!--    <a href="#" class="btn btn-warning">Watch Now</a>-->
<!--  </div>-->
<!--  <video class="card-img-top" src="path/to/video.mp4" controls></video>-->
<!--</div>-->
<div class="card bg-dark text-yellow">
  <div class="card-header">{{movie.name}}</div>
  <div class="card-body">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/VIDEO_ID" allowfullscreen></iframe>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-4">
        <img src="{{movie.img.url}}" class="img-fluid" alt="Movie Poster">
      </div>
      <div class="col-8">
        <h5 class="card-title">{{movie.name}}</h5>
        <h6 class="card-title">{{movie.year}}</h6>
        <p class="card-text">{{movie.desc}}</p>
        <a href="#" class="btn btn-warning text-black">Watch Now</a>

        <a href="{% url 'myapp:updates' movie.id %}" class="btn btn-primary text-black">Update</a>
        <a href="{% url 'myapp:delete' movie.id %}" class="btn btn-danger text-black">Delete</a>







      </div>
    </div>
  </div>
</div>


{% endblock %}

Movie Web Application/web_application/web_project/templates/index.html
{% extends "base.html" %}


{% block title %}Home {% endblock %}
{% block style %}  .moving-text {
      animation: marquee 10s linear infinite;
      white-space: nowrap;
    }

    @keyframes marquee {
      0% {
        transform: translateX(100%);
      }
      100% {
        transform: translateX(-100%);
      }

    }

{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<body>
 <div class="content">

<div id="banner-carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#banner-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#banner-carousel" data-slide-to="1"></li>
    <li data-target="#banner-carousel" data-slide-to="2"></li>
    <li data-target="#banner-carousel" data-slide-to="3"></li>
    <li data-target="#banner-carousel" data-slide-to="4"></li>
  </ol>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '/images/1.jpg' %}" class="d-block w-100" alt="Image 1">
    </div>
    <div class="carousel-item">
      <img src="{% static '/images/2.jpg' %}" class="d-block w-100" alt="Image 2">
    </div>
    <div class="carousel-item">
      <img src="{% static '/images/3.jpg' %}" class="d-block w-100" alt="Image 3">
    </div>
    <div class="carousel-item">
      <img src="{% static '/images/4.jpg' %}"class="d-block w-100" alt="Image 4">
    </div>
    <div class="carousel-item">
      <img src="{% static '/images/5.jpg' %}" class="d-block w-100" alt="Image 5">
    </div>
  </div>

  <a class="carousel-control-prev"  role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#banner-carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</div>
<div class="container-sm">
  <div class="moving-text">
    <h6>This site is created by Jemin Mathew for my education purposes</h6>

  </div>
</div>

{% endblock %}

Movie Web Application/web_application/web_project/templates/movies.html
{% extends "base.html" %}
{% block title %}Movies {% endblock %}

{% block content %}
<div class="container text-center">


{% for i in movies %}

<div class="card text-white bg-dark mx-3 my-3" style="width: 14rem; display: inline-block;">
  <img src="{{i.img.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <h6 class="card-title">{{i.year}}</h6>
    <p class="card-text">{{i.desc}}</p>
    <a href="{%url 'myapp:detail' i.id %}" class="btn btn-warning text-black">Buy</a>
  </div>
</div>

{% endfor %}
</div>
{% endblock %}

Movie Web Application/web_application/web_project/templates/register.html
{% extends "base.html" %}

{% block style %}
.custom-rounded {
  border-radius: 10px;
}
.bg-opacity {
  background-color: rgba(0, 0, 0, 0.5); /* Black color with 70% opacity */
  color: white; /* Text color */
}
{% endblock %}
{% block content %}
<div class="container w-25 text-center  p-3 bg-opacity custom-rounded ">
<div class="container bg-dark p-3 text-white">
  <h2>Sign Up</h2>
  <form>
      <form action="register" method="POST">
    <div class="form-group">
      <label for="firstName">First Name:</label>
      <input type="text" class="form-control" id="firstName" placeholder="Enter first name">
    </div>
    <div class="form-group">
      <label for="lastName">Last Name:</label>
      <input type="text" class="form-control" id="lastName" placeholder="Enter last name">
    </div>
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" class="form-control" id="username" placeholder="Enter username">
    </div>
    <div class="form-group">
      <label for="mobile">Mobile:</label>
      <input type="text" class="form-control" id="mobile" placeholder="Enter mobile number">
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" class="form-control" id="password" placeholder="Enter password">
    </div>
    <div class="form-group">
      <label for="confirmPassword">Confirm Password:</label>
      <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm password">
    </div>
    <div class="form-group">
      <label for="dob">Date of Birth:</label>
      <input type="date" class="form-control" id="dob">
    </div>
    <button type="submit" class="btn btn-warning">Sign Up</button>
    <a href="{% url 'myapp:sign' %}" class="btn btn-primary">Sign In</a>

  </form>
      </form>
</div>
</div>
{% endblock %}

Movie Web Application/web_application/web_project/templates/sign.html
{% extends "base.html" %}

{% block style %}
.custom-rounded {
  border-radius: 10px;
}
.bg-opacity {
  background-color: rgba(0, 0, 0, 0.5); /* Black color with 70% opacity */
  color: white; /* Text color */
}
{% endblock %}
{% block content %}

{% load crispy_forms_tags %}
<div class="container w-25   p-3 bg-opacity custom-rounded text-center ">
<div class="container bg-dark p-3 text-white"><div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary " type="submit">
  <i class="fas fa-sign-in-alt"></i>
</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'credentials:signup' %}">Create an account</a>.</p>
</div>
</div>

</div>
</div>




















{% endblock %}

Movie Web Application/web_application/web_project/templates/sign_up.html
{% extends "base.html" %}

{% block style %}
.custom-rounded {
  border-radius: 10px;
}
.bg-opacity {
  background-color: rgba(0, 0, 0, 0.5); /* Black color with 70% opacity */
  color: white; /* Text color */
}
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container w-25 text-center  p-3 bg-opacity custom-rounded ">
<div class="container bg-dark p-3 text-white">
 <div class="container py-5 ">
	<h1>Sign Up</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-primary" type="submit">
  <i class="fas fa-user-plus"></i>
</button>

	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'credentials:signin' %}">Login</a> instead.</p>
</div>
</div>
</div>
{% endblock %}

Movie Web Application/web_application/web_project/templates/temp.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
   <!DOCTYPE html>
<html>
<head>
  <title>Black and Yellow Background</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    .black-yellow-section {
      background: linear-gradient(45deg, black, yellow);
      padding: 20px;
      color: white;
    }
  </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Navbar content -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Movie Bazar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link text-warning" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

  </nav>


  <div class="black-yellow-section">
    <div class="container">
      <h1>Welcome to the Black and Yellow Section</h1>
      <p>This section has a beautiful background combination of black and yellow.</p>
    </div>
  </div>

  <!-- Footer -->
  <footer class="bg-dark text-white text-center p-3">
     <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2023 Jemin Mathew. All rights reserved.</p>
        </div>
        <div class="col-md-6">
          <ul class="social-icons">
            <li><a href="https://www.linkedin.com/in/jemin-mathew-584908279/"><i class="fab fa-linkedin-in"></i></a></li>

            <li><a href="https://myaccount.google.com/?hl=en"><i class="far fa-envelope"></i></a></li>

            <li><a href="https://github.com/JeminGitHub"><i class="fab fa-github"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  </footer>


  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/your-font-awesome-kit.js" crossorigin="anonymous"></script>
</body>
</html>

Movie Web Application/web_application/web_project/templates/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Update
{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
{{form|crispy}}
  <button type="submit" class="btn btn-warning btn-lg btn-block mb-4">
  Submit
</button>
</form>
{% endblock %}

Movie Web Application/web_application/web_project/templates/user.html
{% extends "base.html" %}
{% load static %}
{% block title %}User {% endblock %}
{% block style %}
.custom-rounded {
  border-radius: 10px;
}
.bg-opacity {
  background-color: rgba(0, 0, 0, 0.5); /* Black color with 70% opacity */
  color: white; /* Text color */
}
{% endblock %}
{% block content %}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<div class="container text-center  p-3 bg-opacity custom-rounded text-left">
<div class="card bg-dark text-dark">
<div class="card">
  <img src="{% static '/images/pp1.jpg' %}" class="card-img-top" alt="Profile Photo">
  <div class="card-body">
    <h5 class="card-title">Jemin Mathew</h5>
    <h6 class="card-subtitle mb-2 text-muted">Python Full Stack Developer</h6>
    <p class="card-text">To kickstart my career in the IT industry as a fresher,
      seeking a challenging position in an esteemed organization.
      I aim to apply and further develop my technical skills and knowledge in software development,
      web development, or database management. With a strong foundation in programming languages and a passion for continuous learning,
      I am eager to contribute to the success of the company by leveraging my problem-solving abilities, teamwork skills, and adaptability. </p>
    <ul class="list-group text-center">
      <li class="list-group-item">Education: Master Of Computer Application <br> Bcom Computer Application</li>
      <li class="list-group-item">Experience: Python Develop Intern @<br> Inmakes Infotech</li>
      <li class="list-group-item">Projects: E-Commerce Project, Hospital Management Project,Movie Web Application<br>Todo Application, Crud Application</li>
  <li class="list-group-item">
  Skills:
  <div class="d-flex justify-content-center">
    <i class="fab fa-python mx-2"></i>
    <i class="fab fa-django mx-2"></i>
    <i class="fab fa-css3-alt mx-2"></i>
    <i class="fab fa-html5 mx-2"></i>
    <i class="fab fa-bootstrap mx-2"></i>
    <i class="fas fa-database mx-2"></i>
    <i class="fab fa-github mx-2"></i>
  </div>
</li>


    </ul>
    </div>
    <a href="https://github.com/JeminGitHub" class="btn btn-primary">
  <i class="fab fa-github"></i> GitHub
</a>

  </div>
</div>

  </div>
</div>


  </div>
</div>

</div>
{% endblock %}